version: "3.8"
services:
  proof-server:
    image: docker.io/midnightntwrk/proof-server:latest
    ports:
      - "6300:6300"
    volumes:
      - ./managed:/app/managed
    environment:
      - PROOF_SERVER_PORT=6300
